
const PASSWORD="aguia2026", DAY_VALUE=10;
const dailyPlans={1:{name:"Segunda-feira",tasks:[["Português","20 min — leitura/interpretação."],["Inglês","20 min — reforço."],["Rosetta Stone","20 min — uma lição."],["Projeto","10 min — prazos e entregas."],["Latim","Oração do mês."],["Desafio do dia","Responder a pergunta diária."]]},2:{name:"Terça-feira",tasks:[["Matemática","20 min — exercícios."],["Arte","20 min — atividade."],["Ciências","10 min — revisão."],["Rosetta Stone","20 min."],["Educação Financeira","10 min."],["Virtudes","Avaliar virtudes do dia."]]},3:{name:"Quarta-feira",tasks:[["Inglês","20 min — vocabulário."],["Português","20 min — escrita."],["História","10 min."],["Rosetta Stone","20 min."],["Leitura","15 min."],["Diário Águia","Gratidão e aprendizado."]]},4:{name:"Quinta-feira",tasks:[["Projeto","20 min."],["Arte","20 min."],["Geografia","10 min."],["Latim","15 min — memorização."],["Educação Financeira","Planejamento."],["Desafio do dia","Responder a pergunta diária."]]},5:{name:"Sexta-feira",tasks:[["Revisão de Inglês","20 min."],["Revisão de Português","20 min."],["Boss Battle","20 questões."],["Teste do responsável","Latim, inglês e escola."],["Organização","Mochila e mesa."],["Diário Águia","Fechamento da semana."]]},6:{name:"Sábado",tasks:[["Opcional","Inglês leve ou leitura."],["Família","Conversar sobre a semana."]]},0:{name:"Domingo",tasks:[["Descanso","Sem cobrança escolar."],["Oração","Recitar oração do mês."]]}};
const virtues=["Organização","Pontualidade","Perseverança","Honestidade","Caridade"];
const grades=[["Inglês",3.3,12,"Crítico"],["Arte",3.8,0,"Crítico"],["Projeto",3.9,0,"Crítico"],["Português",5.3,12,"Atenção"],["Ciências",5.0,8,"Atenção"],["Geografia",6.0,2,"Manutenção"],["História",7.3,0,"Bom"]];
const questionBank={"Inglês":[["In context: John bought a book. O que significa book?",["Livro","Mesa","Casa","Caneta"],0,"Book = livro."],["Complete: I ___ to school every day.",["go","goes","going","gone"],0,"Com I usamos go."],["Good morning significa:",["Boa noite","Bom dia","Boa tarde","Tchau"],1,"Good morning = bom dia."]],"Português":[["Qual alternativa é substantivo?",["Correr","Feliz","Livro","Rapidamente"],2,"Livro é substantivo."],["Frase no passado:",["Eu estudo","Eu estudei","Eu estudarei","Eu estudo agora"],1,"Estudei indica passado."],["Sinônimo de alegre:",["Feliz","Triste","Lento","Baixo"],0,"Alegre = feliz."]],"Matemática":[["Você recebeu R$50 e guardou 20%. Quanto guardou?",["R$5","R$10","R$20","R$25"],1,"20% de 50 = 10."],["7 × 8 =",["54","56","64","58"],1,"7 × 8 = 56."],["Se x+5=12, x =",["5","7","12","17"],1,"x=7."]],"Ciências":[["Órgão que bombeia sangue:",["Pulmão","Coração","Estômago","Rim"],1,"Coração."],["Plantas produzem alimento pela:",["Fotossíntese","Digestão","Evaporação","Sono"],0,"Fotossíntese."]],"História":[["Independência do Brasil:",["1500","1822","1889","1964"],1,"1822."],["República proclamada em:",["1822","1888","1889","1930"],2,"1889."]],"Geografia":[["Capital do Brasil:",["São Paulo","Rio","Brasília","Salvador"],2,"Brasília."],["Bioma do DF:",["Amazônia","Cerrado","Pampa","Caatinga"],1,"Cerrado."]],"Arte":[["Cores primárias tradicionais:",["Vermelho, azul e amarelo","Verde, preto e branco","Roxo e laranja","Cinza e rosa"],0,"Vermelho, azul e amarelo."],["Escultura é:",["Sonora","Tridimensional","Sempre digital","Escrita"],1,"Tridimensional."]],"Projeto":[["Um bom projeto começa com:",["Conclusão","Problema ou pergunta","Cópia","Atraso"],1,"Pergunta/problema."],["Ao pesquisar, devemos:",["Copiar tudo","Ignorar fontes","Registrar fontes","Não revisar"],2,"Registrar fontes."]],"Latim":[["Cognoscere significa:",["Conhecer","Servir","Amar","Correr"],0,"Cognoscere = conhecer."],["Deum significa:",["Deus","Casa","Pai","Livro"],0,"Deum = Deus."],["Pater Noster significa:",["Pai Nosso","Ave Maria","Glória","Credo"],0,"Pai Nosso."]],"Educação Financeira":[["Missão diária vale R$10. Quanto vai para a meta (20%)?",["R$1","R$2","R$5","R$7"],1,"20% de 10 = 2."],["70% de R$10 é:",["R$5","R$6","R$7","R$8"],2,"70% = R$7."],["Hábito que constrói patrimônio:",["Gastar tudo","Comprar por impulso","Poupar regularmente","Ignorar dinheiro"],2,"Poupar regularmente."]]};
const skills={"Inglês":["Vocabulário","Frases","Verbos","Reading","Conversation"],"Latim":["Signum Crucis","Ave Maria","Pater Noster","Gloria Patri","Lema"],"Educação Financeira":["Dinheiro","Poupança","Orçamento","Juros","Investimentos"],"Virtudes":["Organização","Pontualidade","Perseverança","Honestidade","Caridade"]};
const state=JSON.parse(localStorage.getItem("aguiaStateV6")||'{"checked":{},"virtues":{},"quiz":{},"review":[],"xp":0,"streak":0,"money":{},"piggy":{"free":0,"saved":0,"charity":0,"goal":500},"diary":{},"approved":{},"boss":{"active":false,"i":0,"correct":0,"questions":[]}}');
function save(){localStorage.setItem("aguiaStateV6",JSON.stringify(state))}
function iso(d){return d.toISOString().slice(0,10)} function money(n){return"R$ "+Number(n).toFixed(0)} function today(){return iso(new Date())} function plan(d){return dailyPlans[d.getDay()]} function tid(d,i){return iso(d)+"-"+i}
function allQ(){return Object.entries(questionBank).flatMap(([subject,qs])=>qs.map(q=>({subject,q:q[0],a:q[1],c:q[2],e:q[3],raw:q})))}
function dayStats(){let d=new Date(),p=plan(d),done=0;p.tasks.forEach((_,i)=>{if(state.checked[tid(d,i)])done++});return{done,total:p.tasks.length,percent:Math.round(done/p.tasks.length*100),complete:done===p.tasks.length}}
function quizTotals(){let c=0,t=0;Object.values(state.quiz).forEach(s=>{c+=s.correct||0;t+=s.total||0});return{correct:c,total:t,acc:t?Math.round(c/t*100):0}}
function level(xp){if(xp>=1500)return"Nível 6 — Mentor Águia";if(xp>=1000)return"Nível 5 — Águia de Ouro";if(xp>=600)return"Nível 4 — Cavaleiro";if(xp>=300)return"Nível 3 — Guardião";if(xp>=100)return"Nível 2 — Escudeiro";return"Nível 1 — Aspirante"}
function weekMoney(){let sum=0;Object.keys(state.money).forEach(k=>{let d=new Date(k+"T00:00:00"),now=new Date(),diff=(now-d)/86400000;if(diff>=0&&diff<7)sum+=state.money[k]});return sum}
function critical(){let best="Inglês",score=999;grades.forEach(g=>{let q=state.quiz[g[0]]||{correct:0,total:0},acc=q.total?q.correct/q.total*10:5,s=g[1]+acc;if(s<score){score=s;best=g[0]}});return best}
function checkAuth(){if(localStorage.getItem("aguiaUnlocked")==="yes"){lockScreen.classList.add("hidden");appShell.classList.remove("hidden")}}
unlockBtn.onclick=()=>{if(passwordInput.value==="aguia2026"){localStorage.setItem("aguiaUnlocked","yes");checkAuth()}else alert("Senha incorreta.")};passwordInput.addEventListener("keydown",e=>{if(e.key==="Enter")unlockBtn.click()});
function renderMission(){let d=new Date(),p=plan(d),s=dayStats();todayTitle.textContent=p.name+" — missão de hoje";tasks.innerHTML=p.tasks.map((t,i)=>`<label class="task"><input type="checkbox" data-id="${tid(d,i)}" ${state.checked[tid(d,i)]?"checked":""}><span><span class="task-title">${t[0]}</span><br><span class="task-desc">${t[1]}</span></span></label>`).join("");dailyPercent.textContent=s.percent+"%";dailyBar.style.width=s.percent+"%";dailyReward.textContent=state.money[today()]?money(state.money[today()]):"R$ 0";parentDaily.textContent=dailyReward.textContent;parentTasks.textContent=s.done+"/"+s.total;missionStatus.textContent=s.complete?"Missão completa. O responsável já pode aprovar.":"Complete todas as tarefas para liberar R$ 10.";approvalHint.textContent=s.complete?"Chame o responsável para aprovar a missão.":"A recompensa só aparece após completar tudo e receber aprovação.";renderDailyChallenge()}
function renderAI(){let qt=quizTotals(),c=critical(),s=dayStats(),due=state.review.filter(r=>r.due<=today()).length;let msg=`Prioridade de hoje: ${c}. `;if(!s.complete)msg+=`Faltam ${s.total-s.done} tarefa(s) para liberar R$ 10. `;if(due)msg+=`Há ${due} revisão(ões) vencida(s). `;if(qt.total>0&&qt.acc<70)msg+="A taxa de acerto está abaixo de 70%, faça exercícios básicos antes do Boss Battle.";else msg+="Mantenha a constância e finalize a missão diária.";aiMessage.textContent=msg;aiActions.innerHTML=[`Fazer ${c}`,due?`Revisar ${due} erro(s)`:"Sem revisões vencidas",s.complete?"Pedir aprovação":"Concluir tarefas"].map(x=>`<div>${x}</div>`).join("");aiReport.innerHTML=`<div class="stat-row"><strong>Diagnóstico</strong><br><small>${msg}</small></div><div class="stat-row"><strong>Recomendação</strong><br><small>Priorizar ${c}, Rosetta Stone e revisão inteligente.</small></div>`}
function renderDashboard(){let qt=quizTotals();xpTotal.textContent=state.xp+" XP";levelName.textContent=level(state.xp);weekMoney.textContent=money(weekMoney());parentWeek.textContent=money(weekMoney());accuracy.textContent=qt.acc+"%";streak.textContent=state.streak;criticalSubject.textContent=critical()}
function renderDailyChallenge(){let q=allQ()[new Date().getDate()%allQ().length];dailyChallenge.innerHTML=`<p class="quiz-question">${q.q}</p><div class="answers">${q.a.map((a,i)=>`<button class="answer-btn" data-daily="${i}">${a}</button>`).join("")}</div><div id="dailyFeedback" class="feedback hidden"></div>`;window.dailyQuestion=q}
function nextDue(days){let d=new Date();d.setDate(d.getDate()+days);return iso(d)}
function registerAnswer(subject,q,choice,feedbackId,selector){let ok=Number(choice)===q.c,st=state.quiz[subject]||{correct:0,total:0};st.total++;if(ok){st.correct++;state.xp+=5;state.streak++}else{state.streak=0;state.review.push({subject,raw:q.raw,due:nextDue(1)})}state.quiz[subject]=st;save();document.querySelectorAll(selector).forEach(btn=>{let idx=Number(btn.dataset.answer??btn.dataset.daily??btn.dataset.boss);if(idx===q.c)btn.classList.add("correct");if(idx===Number(choice)&&!ok)btn.classList.add("wrong");btn.disabled=true});let f=document.getElementById(feedbackId);f.classList.remove("hidden");f.textContent=ok?"✅ Correto! +5 XP":"❌ Ainda não. "+q.e;setTimeout(renderAll,800)}
function renderSubjects(){let subs=Object.keys(questionBank).sort((a,b)=>(a===critical()?-1:b===critical()?1:0));subjectButtons.innerHTML=subs.map(s=>`<button data-subject="${s}">${s}${s===critical()?" 🔥":""}</button>`).join("")}
let currentSubject=null,currentQ=null;
function pickQ(subject){let due=state.review.find(r=>r.subject===subject&&r.due<=today());if(due)return{subject,q:due.raw[0],a:due.raw[1],c:due.raw[2],e:due.raw[3],raw:due.raw};let arr=questionBank[subject],idx=((state.quiz[subject]?.total||0)+new Date().getDate())%arr.length,q=arr[idx];return{subject,q:q[0],a:q[1],c:q[2],e:q[3],raw:q}}
function renderQuiz(subject){currentSubject=subject;currentQ=pickQ(subject);quizSubject.textContent=subject;quizContent.innerHTML=`<p class="quiz-question">${currentQ.q}</p><div class="answers">${currentQ.a.map((a,i)=>`<button class="answer-btn" data-answer="${i}">${a}</button>`).join("")}</div><div id="quizFeedback" class="feedback hidden"></div>`}
function renderReview(){let due=state.review.filter(r=>r.due<=today());reviewQueue.innerHTML=due.length?due.map(r=>`<div class="review-row"><strong>${r.subject}</strong><br><small>${r.raw[0]}</small></div>`).join(""):`<p class="muted">Nenhuma revisão vencida hoje.</p>`}
function renderSkills(){skillTree.innerHTML=Object.entries(skills).map(([g,arr])=>`<div class="skill-group"><strong>${g}</strong><div class="skill-grid">${arr.map((x,i)=>`<div class="skill ${i<2?'done':'locked'}">${i<2?'✅':'⬜'} ${x}</div>`).join("")}</div></div>`).join("")}
function renderFinance(){let p=state.piggy,perc=Math.min(100,Math.round(p.saved/p.goal*100));freeMoney.textContent=money(p.free);savedMoney.textContent=money(p.saved);charityMoney.textContent=money(p.charity);goalMoney.textContent=money(p.goal);goalPercent.textContent=perc+"%";goalBar.style.width=perc+"%"}
function renderVirtues(){virtueChecks.innerHTML=virtues.map(v=>`<label class="virtue"><input type="checkbox" data-virtue="${v}" ${state.virtues[today()+"-"+v]?"checked":""}><span><strong>${v}</strong><br><small>Praticar esta virtude hoje.</small></span></label>`).join("")}
function renderDiary(){let d=state.diary[today()]||{};gratitude.value=d.gratitude||"";learned.value=d.learned||"";improve.value=d.improve||""}
function startBoss(){let qs=allQ().sort(()=>Math.random()-0.5).slice(0,20);state.boss={active:true,i:0,correct:0,questions:qs};save();renderBoss()}
function renderBoss(){let b=state.boss;bossScore.textContent=(b.correct||0)+"/20";bossMoney.textContent=state.boss.bonus?money(10):"R$ 0";if(!b.active){bossContent.innerHTML="<p class='muted'>Clique em iniciar para começar.</p>";return}let q=b.questions[b.i];if(!q){let ok=b.correct>=16;if(ok&&!b.bonus){state.xp+=50;state.money["boss-"+today()]=10;state.boss.bonus=true}state.boss.active=false;save();bossContent.innerHTML=`<h2>Resultado</h2><p class="quiz-question">${b.correct}/20</p><div class="feedback">${ok?"🏆 Boss derrotado! +50 XP e R$10 bônus.":"Continue treinando. Meta: 16 acertos."}</div>`;renderAll();return}bossContent.innerHTML=`<p class="muted">Questão ${b.i+1}/20 • ${q.subject}</p><p class="quiz-question">${q.q}</p><div class="answers">${q.a.map((a,i)=>`<button class="answer-btn" data-boss="${i}">${a}</button>`).join("")}</div><div id="bossFeedback" class="feedback hidden"></div>`}
function answerBoss(choice){let b=state.boss,q=b.questions[b.i],ok=Number(choice)===q.c;if(ok)b.correct++;document.querySelectorAll("[data-boss]").forEach(btn=>{let idx=Number(btn.dataset.boss);if(idx===q.c)btn.classList.add("correct");if(idx===Number(choice)&&!ok)btn.classList.add("wrong");btn.disabled=true});bossFeedback.classList.remove("hidden");bossFeedback.textContent=ok?"✅ Correto!":"❌ "+q.e;b.i++;save();setTimeout(renderBoss,800)}
function approveMission(){let s=dayStats();if(!s.complete){approvalMsg.textContent="A missão ainda não está completa.";return}if(state.money[today()]){approvalMsg.textContent="Missão já aprovada hoje.";return}state.money[today()]=10;state.xp+=10;state.streak++;state.piggy.free+=7;state.piggy.saved+=2;state.piggy.charity+=1;state.approved[today()]=true;save();approvalMsg.textContent="🦅 Missão aprovada. R$ 10 liberados.";renderAll()}
function renderGrades(){gradesList.innerHTML=grades.map(g=>{let cls=g[1]<5?"danger":g[1]<6?"warn":"ok";return`<div class="grade-row"><div class="grade-head"><strong>${g[0]}</strong><span class="pill ${cls}">${g[1].toFixed(1)}</span></div><small>${g[3]} • ${g[2]} faltas</small><div class="bar"><div style="width:${g[1]*10}%"></div></div></div>`}).join("")}
function renderStats(){let qt=quizTotals();statsBox.innerHTML=`<div class="stat-row"><strong>XP</strong><br><small>${state.xp} XP • ${level(state.xp)}</small></div><div class="stat-row"><strong>Exercícios</strong><br><small>${qt.correct}/${qt.total} acertos • ${qt.acc}%</small></div><div class="stat-row"><strong>Dinheiro</strong><br><small>${money(weekMoney())} nesta semana • ${money(state.piggy.saved)} guardados</small></div>`;badges.innerHTML=[["🥉 100 XP","Disciplina inicial"],["🥈 Pequeno Investidor","R$100 guardados"],["🥇 30 dias","Constância"],["🏆 Mestre do Inglês","80% acertos"],["✝️ Guardião do Latim","Orações"],["🦅 Águia de Ouro","Sem recuperação"],["🌟 Virtudes","Caráter"],["📖 Diário Águia","Reflexão"]].map(b=>`<span>${b[0]}<br><small>${b[1]}</small></span>`).join("")}
function switchTab(tab){document.querySelectorAll(".panel").forEach(p=>p.classList.remove("active"));document.getElementById(tab).classList.add("active");document.querySelectorAll("[data-tab]").forEach(b=>b.classList.toggle("active",b.dataset.tab===tab));renderAll()}
function renderAll(){renderMission();renderAI();renderDashboard();renderSubjects();renderReview();renderSkills();renderFinance();renderVirtues();renderDiary();renderBoss();renderGrades();renderStats()}
document.addEventListener("change",e=>{if(e.target.matches("#tasks input")){state.checked[e.target.dataset.id]=e.target.checked;save();renderAll()}if(e.target.matches("[data-virtue]")){state.virtues[today()+"-"+e.target.dataset.virtue]=e.target.checked;save();renderAll()}});
document.addEventListener("click",e=>{if(e.target.matches("[data-tab]"))switchTab(e.target.dataset.tab);if(e.target.matches("[data-subject],.subject-shortcut")){switchTab("academy");renderQuiz(e.target.dataset.subject)}if(e.target.matches("[data-answer]"))registerAnswer(currentSubject,currentQ,e.target.dataset.answer,"quizFeedback","[data-answer]");if(e.target.matches("[data-daily]"))registerAnswer(window.dailyQuestion.subject,window.dailyQuestion,e.target.dataset.daily,"dailyFeedback","[data-daily]");if(e.target.id==="requestApproval")switchTab("parent");if(e.target.id==="approveMission")approveMission();if(e.target.id==="startBoss")startBoss();if(e.target.matches("[data-boss]"))answerBoss(e.target.dataset.boss);if(e.target.id==="saveDiary"){state.diary[today()]={gratitude:gratitude.value,learned:learned.value,improve:improve.value};save();alert("Diário salvo.")}if(e.target.id==="exportData"){let blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),state},null,2)],{type:"application/json"});let a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="projeto-aguia-v6-progresso.json";a.click()}if(e.target.id==="logout"){localStorage.removeItem("aguiaUnlocked");location.reload()}});
if("serviceWorker"in navigator)navigator.serviceWorker.register("service-worker.js");checkAuth();renderAll();
