
const PASSWORD="aguia2026", XP_TASK=10, XP_CORRECT=5, XP_DAILY=10, XP_BOSS=50;
const dailyPlans={1:{name:"Segunda-feira",tasks:[["Português","20 min — leitura, interpretação ou gramática."],["Inglês","20 min — reforço para recuperar a nota."],["Projeto","10 min — organizar pesquisa ou entrega."],["Rosetta Stone","20 min — uma lição completa."],["Latim","5 min — oração do mês."]]},2:{name:"Terça-feira",tasks:[["Matemática","20 min — exercícios."],["Arte","20 min — atividade prática."],["Ciências","10 min — revisão."],["Rosetta Stone","20 min — lição completa."],["Educação Financeira","10 min — cofrinho e exercício."]]},3:{name:"Quarta-feira",tasks:[["Inglês","20 min — vocabulário."],["Português","20 min — escrita."],["História","10 min — manutenção."],["Rosetta Stone","20 min — lição completa."],["Leitura","15 min — leitura livre."]]},4:{name:"Quinta-feira",tasks:[["Projeto","20 min — avançar entrega."],["Arte","20 min — finalizar tarefa."],["Geografia","10 min — manutenção."],["Latim","15 min — repetir oração."],["Educação Financeira","10 min — planejamento."]]},5:{name:"Sexta-feira",tasks:[["Revisão de Inglês","20 min."],["Revisão de Português","20 min."],["Boss Battle","20 questões mistas."],["Teste do responsável","Latim, inglês e perguntas."],["Organização","Mochila e mesa."]]},6:{name:"Sábado",tasks:[["Opcional","Filme, desenho ou música em inglês."],["Conversa familiar","Avaliar a semana."]]},0:{name:"Domingo",tasks:[["Descanso","Sem cobrança escolar."],["Oração","Recitar a oração do mês."]]}};
const months=[["Junho","Signum Crucis","Saudações, números e cores","Português, Inglês e Arte"],["Julho","Ave Maria — primeira parte","Família e objetos","Inglês, Projeto e Matemática"],["Agosto","Ave Maria completa","Rotina e escola","Inglês, Português e Ciências"],["Setembro","Pater Noster — primeira parte","Verbos básicos","Projeto, Arte e provas"],["Outubro","Pater Noster completo","Diálogos simples","Preparação final"],["Novembro","Gloria Patri","Revisão geral","Fechamento do ano"],["Dezembro","Revisão geral","Apresentação de 2 minutos","Águia de Ouro"]];
const grades=[["Inglês",3.3,12,"Crítico: Rosetta Stone diário + exercícios"],["Arte",3.8,0,"Crítico: organizar entregas"],["Projeto",3.9,0,"Crítico: acompanhar prazos"],["Português",5.3,12,"Atenção: leitura e produção"],["Ciências",5.0,8,"Atenção: revisão"],["Ensino Religioso",5.0,0,"Manutenção"],["Geografia",6.0,2,"Manutenção"],["História",7.3,0,"Bom desempenho"]];
const questionBank={
"Inglês":[["Qual a tradução de book?",["Mesa","Livro","Casa","Escola"],1,"Book = livro."],["Como se diz bom dia?",["Good night","Good morning","Good afternoon","Bye"],1,"Good morning = bom dia."],["Complete: I ___ to school.",["go","goes","going","gone"],0,"Com I usamos go."],["Qual significa Eu gosto de estudar?",["I like to study","I live in Brazil","I am tired","I have a dog"],0,"I like to study."],["Plural de child:",["Childs","Children","Childes","Childrens"],1,"Child → children."]],
"Latim":[["Complete: In nomine ___, et Filii.",["Patris","Mariae","Regis","Pacis"],0,"Patris."],["Pater Noster significa:",["Ave Maria","Pai Nosso","Glória ao Pai","Credo"],1,"Pater Noster = Pai Nosso."],["Ave Maria começa com:",["Gloria Patri","Ave Maria, gratia plena","Credo","Pater noster"],1,"Ave Maria, gratia plena."],["Deum significa:",["Deus","Casa","Livro","Pai"],0,"Deum = Deus."]],
"Português":[["Qual alternativa possui substantivo?",["Correr","Feliz","Livro","Rapidamente"],2,"Livro é substantivo."],["Qual opção tem verbo?",["Casa","Bonito","Estudar","Azul"],2,"Estudar é verbo."],["Frase no passado:",["Eu estudo hoje","Eu estudarei","Eu estudei ontem","Eu estudo agora"],2,"Estudei indica passado."],["Sinônimo de alegre:",["Triste","Feliz","Rápido","Baixo"],1,"Alegre = feliz."]],
"Matemática":[["25% de 200 é:",["25","40","50","100"],2,"25% de 200 = 50."],["7 × 8 =",["54","56","64","58"],1,"7 × 8 = 56."],["Se x + 5 = 12, x =",["5","7","12","17"],1,"x = 7."],["Metade de 90 é:",["30","40","45","50"],2,"90/2 = 45."]],
"Ciências":[["Órgão que bombeia sangue:",["Pulmão","Coração","Estômago","Rim"],1,"Coração."],["Plantas produzem alimento pela:",["Fotossíntese","Digestão","Evaporação","Sono"],0,"Fotossíntese."],["Água ferve perto de:",["0°C","50°C","100°C","200°C"],2,"100°C ao nível do mar."]],
"História":[["Independência do Brasil:",["1500","1822","1889","1964"],1,"Foi em 1822."],["Proclamação da República:",["1822","1888","1889","1930"],2,"Foi em 1889."]],
"Geografia":[["Capital do Brasil:",["São Paulo","Rio","Brasília","Salvador"],2,"Brasília."],["Bioma do DF:",["Amazônia","Cerrado","Pampa","Caatinga"],1,"Cerrado."]],
"Arte":[["Cores primárias tradicionais:",["Vermelho, azul e amarelo","Verde, preto e branco","Roxo e laranja","Cinza e rosa"],0,"Vermelho, azul e amarelo."],["Escultura é obra:",["Sonora","Tridimensional","Sempre digital","Escrita"],1,"Tridimensional."]],
"Projeto":[["Um bom projeto começa com:",["Conclusão","Problema ou pergunta","Cópia","Atraso"],1,"Começa com uma pergunta/problema."],["Ao pesquisar, devemos:",["Copiar tudo","Ignorar fontes","Registrar fontes","Não revisar"],2,"Registrar fontes."]],
"Educação Financeira":[["Ganhou R$50 e guardou R$20. Sobrou:",["R$20","R$30","R$40","R$50"],1,"50 - 20 = 30."],["Meta de R$300 poupando R$50/mês. Tempo:",["4 meses","5 meses","6 meses","7 meses"],2,"300/50 = 6."],["Hábito que constrói patrimônio:",["Comprar por impulso","Poupar regularmente","Gastar tudo","Fazer dívidas"],1,"Poupar regularmente."],["70% de R$50 é:",["R$25","R$30","R$35","R$40"],2,"70% de 50 = 35."],["Juros são:",["Dinheiro emprestado ou rendimento sobre capital","Sempre desconto","Só moedas","Nota escolar"],0,"Juros envolvem capital ao longo do tempo."]]
};
const skills={"Inglês":["Saudações","Números","Cores","Família","Verbos","Present Simple","Reading"],"Latim":["Signum Crucis","Ave Maria","Pater Noster","Gloria Patri"],"Educação Financeira":["Dinheiro","Poupança","Orçamento","Juros","Investimentos","Consumo consciente"]};
const state=JSON.parse(localStorage.getItem("aguiaStateV5")||'{"checked":{},"quiz":{},"xp":0,"lives":5,"streak":0,"answeredDaily":{},"review":[],"piggy":{"saved":0,"free":0,"charity":0,"goal":250},"boss":{"active":false,"i":0,"correct":0,"questions":[]},"approved":false}');
function save(){localStorage.setItem("aguiaStateV5",JSON.stringify(state))}
function money(n){return"R$ "+Number(n).toFixed(0)} function iso(d){return d.toISOString().slice(0,10)} function plan(d){return dailyPlans[d.getDay()]} function tid(d,i){return iso(d)+"-"+i}
function weekDates(){const n=new Date(),day=n.getDay()||7,m=new Date(n);m.setDate(n.getDate()-day+1);return Array.from({length:7},(_,i)=>{const d=new Date(m);d.setDate(m.getDate()+i);return d})}
function dayStats(d){let p=plan(d),done=0;p.tasks.forEach((_,i)=>{if(state.checked[tid(d,i)])done++});return{done,total:p.tasks.length,percent:Math.round(done/p.tasks.length*100)}}
function weekStats(){let done=0,total=0;weekDates().slice(0,5).forEach(d=>{let s=dayStats(d);done+=s.done;total+=s.total});let percent=total?Math.round(done/total*100):0;return{done,total,percent}}
function reward(p){if(p>=100)return 50;if(p>=90)return 45;if(p>=80)return 40;if(p>=70)return 30;return 0}
function level(xp){if(xp>=1500)return"Nível 6 — Mentor Águia";if(xp>=1000)return"Nível 5 — Águia de Ouro";if(xp>=600)return"Nível 4 — Cavaleiro";if(xp>=300)return"Nível 3 — Guardião";if(xp>=100)return"Nível 2 — Escudeiro";return"Nível 1 — Aspirante"}
function totals(){let c=0,t=0;Object.values(state.quiz).forEach(s=>{c+=s.correct||0;t+=s.total||0});return{correct:c,total:t,acc:t?Math.round(c/t*100):0}}
function critical(){let worst=grades[0][0],score=999;grades.forEach(g=>{let q=state.quiz[g[0]]||{correct:0,total:0};let acc=q.total?q.correct/q.total*10:5;let s=g[1]+acc;if(s<score){score=s;worst=g[0]}});return worst}
function normalize(q){return{q:q[0],a:q[1],c:q[2],e:q[3]}}
function allQuestions(){return Object.entries(questionBank).flatMap(([subject,qs])=>qs.map(q=>({subject,...normalize(q)})))}
function checkAuth(){if(localStorage.getItem("aguiaUnlocked")==="yes"){lockScreen.classList.add("hidden");appShell.classList.remove("hidden")}}
unlockBtn.onclick=()=>{if(passwordInput.value===PASSWORD){localStorage.setItem("aguiaUnlocked","yes");checkAuth()}else alert("Senha incorreta.")};passwordInput.addEventListener("keydown",e=>{if(e.key==="Enter")unlockBtn.click()});
function renderToday(){let d=new Date(),p=plan(d);todayTitle.textContent=p.name+" — rotina de hoje";nextTask.textContent="Próxima atividade: "+(p.tasks.find((_,i)=>!state.checked[tid(d,i)])?.[0]||"todas concluídas");tasks.innerHTML=p.tasks.map((t,i)=>`<label class="task"><input type="checkbox" data-id="${tid(d,i)}" ${state.checked[tid(d,i)]?"checked":""}><span><span class="task-title">${t[0]}</span><br><span class="task-desc">${t[1]}</span></span></label>`).join("");renderDaily()}
function renderTutor(){let c=critical();tutorMessage.textContent=`Hoje a prioridade é ${c}. Sugestão: faça exercícios dessa matéria e revise os erros antes de terminar o dia.`}
function dailyQ(){let qs=allQuestions();return qs[new Date().getDate()%qs.length]}
function renderDaily(){let q=dailyQ(),key=iso(new Date()),ans=state.answeredDaily[key];dailyChallenge.innerHTML=`<p class="quiz-question">${q.q}</p><div class="answers">${q.a.map((x,i)=>`<button class="answer-btn" data-daily="${i}" ${ans?'disabled':''}>${x}</button>`).join("")}</div><div id="dailyFeedback" class="feedback ${ans?'':'hidden'}">${ans?'Desafio do dia já respondido.':''}</div>`}
let currentSubject=null,currentQuestionIndex=0;
function renderSubjects(){let order=Object.keys(questionBank).sort((a,b)=>(a===critical()?-1:b===critical()?1:0));subjectButtons.innerHTML=order.map(s=>`<button data-subject="${s}">${s}${s===critical()?" 🔥":""}</button>`).join("")}
function pickQuestion(subject){let qs=questionBank[subject];let due=state.review.find(r=>r.subject===subject && r.due<=iso(new Date()));if(due)return {review:due,...normalize(due.raw)};let idx=((state.quiz[subject]?.total||0)+new Date().getDate())%qs.length;return normalize(qs[idx])}
function renderQuiz(subject){currentSubject=subject;let q=pickQuestion(subject);window.currentQuestion=q;quizSubject.textContent=subject;quizContent.innerHTML=`<p class="quiz-question">${q.q}</p><div class="answers">${q.a.map((x,i)=>`<button class="answer-btn" data-answer="${i}">${x}</button>`).join("")}</div><div id="quizFeedback" class="feedback hidden"></div>`}
function answerQuiz(choice){let q=window.currentQuestion;if(!q||!currentSubject)return;let st=state.quiz[currentSubject]||{correct:0,total:0};st.total++;let ok=Number(choice)===q.c;if(ok){st.correct++;state.xp+=5;state.streak++;if(state.streak%10===0)state.lives=Math.min(5,state.lives+1);state.review=state.review.filter(r=>!(r.subject===currentSubject&&r.raw&&r.raw[0]===q.q))}else{state.streak=0;state.lives=Math.max(0,state.lives-1);let raw=[q.q,q.a,q.c,q.e];state.review.push({subject:currentSubject,raw,due:nextDue(1)})}state.quiz[currentSubject]=st;save();showAnswer(choice,ok,q,"quizFeedback","[data-answer]");setTimeout(()=>{renderQuiz(currentSubject);renderAll()},1200)}
function nextDue(days){let d=new Date();d.setDate(d.getDate()+days);return iso(d)}
function showAnswer(choice,ok,q,feedbackId,selector){document.querySelectorAll(selector).forEach(btn=>{let idx=Number(btn.dataset.answer??btn.dataset.daily);if(idx===q.c)btn.classList.add("correct");if(idx===Number(choice)&&!ok)btn.classList.add("wrong");btn.disabled=true});let f=document.getElementById(feedbackId);f.classList.remove("hidden");f.textContent=ok?"✅ Correto! XP conquistado.":"❌ Ainda não. "+q.e}
function answerDaily(choice){let q=dailyQ(),key=iso(new Date());if(state.answeredDaily[key])return;let st=state.quiz[q.subject]||{correct:0,total:0};st.total++;let ok=Number(choice)===q.c;if(ok){st.correct++;state.xp+=10;state.streak++}else{state.streak=0;state.lives=Math.max(0,state.lives-1);state.review.push({subject:q.subject,raw:[q.q,q.a,q.c,q.e],due:nextDue(1)})}state.quiz[q.subject]=st;state.answeredDaily[key]=ok?"correct":"wrong";save();showAnswer(choice,ok,q,"dailyFeedback","[data-daily]");renderAll()}
function renderReview(){let due=state.review.filter(r=>r.due<=iso(new Date()));reviewQueue.innerHTML=due.length?due.slice(0,5).map(r=>`<div class="review-row"><strong>${r.subject}</strong><br><small>${r.raw[0]}</small></div>`).join(""):`<p class="muted">Nenhuma revisão vencida hoje.</p>`}
function renderPerf(){subjectPerformance.innerHTML=Object.keys(questionBank).map(s=>{let st=state.quiz[s]||{correct:0,total:0},acc=st.total?Math.round(st.correct/st.total*100):0;return`<div class="perf-row"><div class="perf-head"><strong>${s}</strong><span class="pill">${st.correct}/${st.total}</span></div><small>${acc}% de acertos</small><div class="bar"><div style="width:${acc}%"></div></div></div>`}).join("")}
function renderDashboard(){let s=weekStats(),r=reward(s.percent),qt=totals();["dashboardPercent","parentPercent"].forEach(id=>document.getElementById(id).textContent=s.percent+"%");dashboardBar.style.width=s.percent+"%";weekRewardTop.textContent=money(r);parentReward.textContent=money(r);parentQuiz.textContent=qt.correct+"/"+qt.total;parentCritical.textContent=critical();xpTotal.textContent=state.xp+" XP";levelName.textContent=level(state.xp);lives.textContent="❤️".repeat(state.lives)+"🤍".repeat(5-state.lives);accuracy.textContent=qt.acc+"%";streak.textContent=state.streak;let start=new Date(new Date().getFullYear(),5,1),end=new Date(new Date().getFullYear(),11,31),now=new Date(),total=end-start,passed=Math.max(0,Math.min(total,now-start)),days=Math.ceil((end-now)/86400000);daysLeft.textContent=days>0?`Faltam ${days} dias para concluir a missão 2026.`:"Missão 2026 concluída.";annualBar.style.width=Math.round(passed/total*100)+"%"}
function renderFinance(){let p=state.piggy,percent=Math.min(100,Math.round(p.saved/p.goal*100));piggySaved.textContent=money(p.saved);piggyFree.textContent=money(p.free);piggyCharity.textContent=money(p.charity);piggyGoal.textContent=money(p.goal);piggyPercent.textContent=percent+"%";piggyBar.style.width=percent+"%"}
let bossQ=null;
function startBoss(){let qs=allQuestions().sort(()=>Math.random()-0.5).slice(0,20);state.boss={active:true,i:0,correct:0,questions:qs};save();renderBoss()}
function renderBoss(){let b=state.boss;bossScore.textContent=(b.correct||0)+"/20";if(!b.active){bossContent.innerHTML="<p class='muted'>Clique em iniciar para começar.</p>";return}let q=b.questions[b.i];if(!q){let ok=b.correct>=16;if(ok)state.xp+=50;state.boss.active=false;save();bossContent.innerHTML=`<h2>Resultado final</h2><p class="quiz-question">${b.correct}/20</p><div class="feedback">${ok?"🏆 Ouro! +50 XP":"Continue treinando. Meta: 16 acertos."}</div>`;renderAll();return}bossContent.innerHTML=`<p class="muted">Questão ${b.i+1}/20 • ${q.subject}</p><p class="quiz-question">${q.q}</p><div class="answers">${q.a.map((x,i)=>`<button class="answer-btn" data-boss="${i}">${x}</button>`).join("")}</div><div id="bossFeedback" class="feedback hidden"></div>`}
function answerBoss(choice){let b=state.boss,q=b.questions[b.i],ok=Number(choice)===q.c;if(ok)b.correct++;showAnswer(choice,ok,q,"bossFeedback","[data-boss]");b.i++;save();setTimeout(renderBoss,900)}
function renderGrades(){gradesList.innerHTML=grades.map(g=>{let cls=g[1]<5?"danger":g[1]<6?"warn":"ok";return`<div class="grade-row"><div class="grade-head"><strong>${g[0]}</strong><span class="pill ${cls}">${g[1].toFixed(1)}</span></div><small>${g[3]}</small><div class="bar"><div style="width:${g[1]*10}%"></div></div></div>`}).join("");absenceList.innerHTML=grades.filter(g=>g[2]>0).map(g=>`<div class="absence-row"><strong>${g[0]}</strong><br><small>${g[2]} faltas registradas.</small></div>`).join("")}
function renderJourney(){months.innerHTML=monthsData();skillTree.innerHTML=Object.entries(skills).map(([g,arr])=>`<div class="skill-group"><strong>${g}</strong><div class="skill-grid">${arr.map((x,i)=>`<div class="skill ${i<2?'done':'locked'}">${i<2?'✅':'⬜'} ${x}</div>`).join("")}</div></div>`).join("");badges.innerHTML=[["🥉 Bronze","100 XP"],["🥈 Pequeno Investidor","R$100 guardados"],["🥇 30 dias","Constância"],["🏆 Guardião do Latim","4 orações"],["🇺🇸 Mestre do Inglês","80% acertos"],["💰 Pequeno Investidor","Meta financeira"],["🧠 100 exercícios","Prática"],["🦅 Águia de Ouro","Sem recuperação"]].map(b=>`<span>${b[0]}<br><small>${b[1]}</small></span>`).join("")}
function monthsData(){return months.map(m=>`<div class="month"><strong>${m[0]}</strong><small>Latim: ${m[1]}</small><small>Inglês: ${m[2]}</small><small>Foco: ${m[3]}</small></div>`).join("")}
function renderWeek(){/* kept for future */}
function renderReport(){let qt=totals();weeklyReport.innerHTML=`<div class="absence-row"><strong>Exercícios</strong><br><small>${qt.total} questões • ${qt.correct} acertos • ${qt.acc}%</small></div><div class="absence-row"><strong>XP</strong><br><small>${state.xp} XP • ${level(state.xp)}</small></div><div class="absence-row"><strong>Sugestão</strong><br><small>Reforçar ${critical()} e revisar erros pendentes.</small></div>`}
function switchTab(tab){document.querySelectorAll(".panel").forEach(p=>p.classList.remove("active"));document.getElementById(tab).classList.add("active");document.querySelectorAll("[data-tab]").forEach(b=>b.classList.toggle("active",b.dataset.tab===tab));renderAll()}
function renderAll(){renderToday();renderTutor();renderSubjects();renderReview();renderPerf();renderDashboard();renderFinance();renderBoss();renderGrades();renderJourney();renderReport()}
document.addEventListener("change",e=>{if(e.target.matches("#tasks input")){let was=!!state.checked[e.target.dataset.id];state.checked[e.target.dataset.id]=e.target.checked;if(e.target.checked&&!was)state.xp+=10;if(!e.target.checked&&was)state.xp=Math.max(0,state.xp-10);save();renderAll()}})
document.addEventListener("click",e=>{if(e.target.matches("[data-tab]"))switchTab(e.target.dataset.tab);if(e.target.matches("[data-subject],.subject-shortcut")){switchTab("quiz");renderQuiz(e.target.dataset.subject)}if(e.target.matches("[data-answer]"))answerQuiz(e.target.dataset.answer);if(e.target.matches("[data-daily]"))answerDaily(e.target.dataset.daily);if(e.target.id==="startBoss")startBoss();if(e.target.matches("[data-boss]"))answerBoss(e.target.dataset.boss);if(e.target.id==="addRewardToPiggy"){let r=reward(weekStats().percent);state.piggy.free+=r*.7;state.piggy.saved+=r*.2;state.piggy.charity+=r*.1;save();renderAll()}if(e.target.id==="approveWeek"){state.approved=true;save();approvalMsg.textContent="Semana aprovada pelo responsável."}if(e.target.id==="logout"){localStorage.removeItem("aguiaUnlocked");location.reload()}if(e.target.id==="exportData"){let blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),state},null,2)],{type:"application/json"});let a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="projeto-aguia-v5-progresso.json";a.click()}if(e.target.id==="saveDay")alert("Dia salvo. Continue firme na jornada!")});
if("serviceWorker"in navigator)navigator.serviceWorker.register("service-worker.js");checkAuth();renderAll();
