
const PASSWORD='aguia2026';
const gradesDataArr=[['Matemática',3.3,5],['Inglês',3.3,5],['Projeto',3.3,5],['Ciências',5.0,4],['Arte',5.0,3],['Português',6.7,2],['Geografia',6.0,1],['História',7.3,1]];
const subjectIcons={'Matemática':'🧮','Inglês':'🇺🇸','Projeto':'💡','Catecismo':'✝️','Latim':'🏛️','Ed. Financeira':'💰','Português':'📝','Ciências':'🔬','Geografia':'🌎','História':'🏛️','Arte':'🎨'};
const curriculum={Matemática:['Porcentagem','Equações','Funções','Estatística','Geometria'],Português:['Interpretação textual','Produção textual','Gramática contextualizada','Gêneros textuais'],Ciências:['Genética','Ecologia','Corpo humano','Sustentabilidade'],História:['República Brasileira','Guerras Mundiais','História Contemporânea'],Geografia:['Globalização','Geopolítica','Economia mundial','Questões ambientais'],Inglês:['Reading','Vocabulário','Verbos','Interpretação de textos curtos'],Arte:['Artes visuais','Música','Artes cênicas','Leitura de imagens'],Projeto:['Pesquisa','Fontes','Produção escrita','Apresentação oral']};
const plans={1:['Segunda-feira','Gramática','gram',[['Português','Interpretação e gramática'],['Inglês','Vocabulário e reading'],['Rosetta Stone','20 minutos'],['Latim','Oração do mês'],['Exercício','Quiz de gramática'],['Finanças','Registrar recompensa se aprovado']]],2:['Terça-feira','Dialética','dial',[['Matemática','Porcentagem, equações ou funções'],['Ciências','Genética, ecologia ou corpo humano'],['Educação Financeira','Problema prático'],['Exercício','Quiz de raciocínio'],['Revisão','Questões erradas'],['Virtude','Perseverança']]],3:['Quarta-feira','Retórica','rhet',[['Projeto','Pesquisa e organização'],['Português','Produção de texto curto'],['Apresentação oral','Explicar ao responsável'],['Inglês','Frases simples'],['Diário Águia','O que aprendi hoje?'],['Exercício','Argumentação']]],4:['Quinta-feira','Quadrivium','quad',[['Geometria','Número no espaço'],['Geografia','Mapas, economia ou ambiente'],['Arte','Forma, imagem e proporção'],['Astronomia/Ciências','Tempo e movimento'],['Latim cantado','Gloria Patri'],['Exercício','Quiz do Quadrivium']]],5:['Sexta-feira','Síntese','syn',[['Revisão geral','Matemática, Inglês e Projeto'],['Boss Battle','20 questões'],['Simulado curto','3º/4º bimestre'],['Organização','Material e pendências'],['Relatório','Responsável confere'],['Diário','Fechamento semanal']]],6:['Sábado','Catecismo','cat',[['Catecismo','Leitura São Pio X'],['Perguntas','3 perguntas e respostas'],['Oração','Credo ou Sinal da Cruz'],['Reflexão','O que aprendi sobre Deus?'],['Latim','Uma oração em latim']]],0:['Domingo','Vida Cristã','cat',[['Missa','Participar da Santa Missa'],['Catecismo','Revisão breve'],['Orações','Pai Nosso, Ave Maria, Glória e Salve Rainha'],['Diário espiritual','Gratidão e propósito'],['Família','Conversar sobre a semana']]]};
const qs={Matemática:[['15% de 200 é:',['15','20','30','50'],2,'15% = 0,15; 0,15 × 200 = 30.']],Inglês:[['Book significa:',['Mesa','Livro','Casa','Caneta'],1,'Book = livro.']],Projeto:[['Um projeto começa com:',['Cópia','Pergunta ou problema','Atraso'],1,'Começa com uma pergunta/problema.']],Catecismo:[['As partes principais da Doutrina Cristã são:',['Credo, Padre-Nosso, Mandamentos e Sacramentos','Somente Latim','Somente História'],0,'São quatro partes principais.']],Latim:[['Cognoscere significa:',['Conhecer','Amar','Servir'],0,'Cognoscere = conhecer.']],'Ed. Financeira':[['20% de R$10 é:',['R$1','R$2','R$5'],1,'20% de 10 = R$2.']],Português:[['O objetivo da interpretação textual é:',['Copiar','Compreender','Somar'],1,'Interpretar é compreender o texto.']],Ciências:[['DNA está ligado a:',['Genética','Música','Mapa'],0,'DNA é assunto de genética.']],Geografia:[['Globalização envolve:',['Integração mundial','Somente verbos','Somente números'],0,'Globalização envolve integração mundial.']],História:[['República no Brasil foi proclamada em:',['1822','1889','1930'],1,'Foi em 1889.']],Arte:[['Geometria ajuda a Arte com:',['Forma e proporção','Conjugação','Juros'],0,'Forma e proporção são bases visuais.']]};
const journeyPages=[{emoji:'🦅',title:'Olá, João!',text:'Eu sou a Águia.\n\nVou acompanhar você durante toda essa aventura.\n\n📚 Aprender\n🧠 Ficar mais inteligente\n⭐ Ganhar experiência\n💰 Conquistar recompensas\n❤️ Crescer como pessoa'},{emoji:'🎯',title:'Sua Missão',text:'Todo dia você terá uma missão.\n\n☑ Português\n☑ Matemática\n☑ Inglês\n☑ Latim\n☑ Exercício\n\nQuando terminar tudo, chame um responsável.'},{emoji:'💰',title:'Como ganhar seus R$ 10',text:'Faça todas as tarefas, resolva o desafio e chame um responsável.\n\nEle aperta APROVAR MISSÃO.\n\n🏆 Você ganhou R$ 10.'},{emoji:'🤖',title:'Automação com IA',text:'O Planejador Águia olha suas tarefas, notas e progresso.\n\nEle sugere o que estudar amanhã.\n\nVocê também pode copiar um relatório para usar com uma IA externa.'},{emoji:'🚀',title:'Começar minha missão',text:'Cognoscere, amare et servire Deum.\n\nConhecer. Amar. Servir a Deus.'}];
let state=JSON.parse(localStorage.getItem('aguiaV10')||'{"checked":{},"money":{},"xp":0,"answers":{},"piggy":{"free":0,"saved":0,"charity":0,"goal":500},"journeyIndex":0,"aiPlan":""}');
function save(){localStorage.setItem('aguiaV10',JSON.stringify(state))}
function iso(d){return d.toISOString().slice(0,10)} function today(){return iso(new Date())} function money(n){return 'R$ '+Number(n).toFixed(0)} function plan(d){return plans[d.getDay()]} function tid(d,i){return iso(d)+'-'+i}
function stats(d=new Date()){let p=plan(d),done=0;p[3].forEach((_,i)=>{if(state.checked[tid(d,i)])done++});return{done,total:p[3].length,pct:Math.round(done/p[3].length*100),complete:done===p[3].length}}
function critical(){return gradesDataArr.slice().sort((a,b)=>a[1]-b[1])[0][0]} function weekDates(){let n=new Date(),day=n.getDay()||7,m=new Date(n);m.setDate(n.getDate()-day+1);return Array.from({length:7},(_,i)=>{let d=new Date(m);d.setDate(m.getDate()+i);return d})} function weekMoney(){return Object.values(state.money).reduce((a,b)=>a+b,0)}
function switchTab(tab){document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));document.getElementById(tab).classList.add('active');document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));renderAll()}
enter.onclick=()=>{if(pass.value===PASSWORD){localStorage.setItem('unlockedV10','yes');lock.classList.add('hidden');app.classList.remove('hidden');firstRun()}else alert('Senha incorreta')};if(localStorage.getItem('unlockedV10')==='yes'){lock.classList.add('hidden');app.classList.remove('hidden')}
function firstRun(){if(!localStorage.getItem('journeySeenV10')){localStorage.setItem('journeySeenV10','started');state.journeyIndex=0;save();switchTab('journey')}}
setTimeout(firstRun,200);
function renderMission(){let d=new Date(),p=plan(d),s=stats(d);todayTitle.textContent=p[0]+' — '+p[1];tasks.innerHTML=p[3].map((t,i)=>`<label class="task"><input type="checkbox" data-id="${tid(d,i)}" ${state.checked[tid(d,i)]?'checked':''}><span><b>${t[0]}</b><small>${t[1]}</small></span></label>`).join('');dayPct.textContent=s.pct+'%';dayBar.style.width=s.pct+'%';todayMoney.textContent=state.money[today()]?money(10):'R$ 0';missionText.textContent=s.complete?'Missão completa. Peça aprovação.':'Complete tudo para liberar R$ 10.';tasksDone.textContent=s.done+'/'+s.total}
function renderEagleMessage(){let s=stats(),p=plan(new Date());let msgs=[`Hoje é dia de ${p[1]}. Vamos voar mais alto!`,`Faltam ${Math.max(0,s.total-s.done)} tarefa(s) para completar a missão.`,`Use a aba IA para gerar o plano de amanhã.`,`Cognoscere, amare et servire Deum.`];eagleMessage.textContent=msgs[new Date().getDate()%msgs.length]}
function generateAIPlan(){let c=critical(),s=stats(),doneMoney=state.money[today()]?10:0;let tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+1);let tp=plan(tomorrow);let extra=c==='Matemática'?'Resolver 5 questões de porcentagem/equações.':c==='Inglês'?'Fazer 20 minutos de Rosetta Stone e 5 frases.':`Reforçar ${c} com 3 exercícios.`;state.aiPlan=`Plano automático do Tutor Águia\n\nPrioridade do boletim: ${c}\nProgresso de hoje: ${s.done}/${s.total} tarefas (${s.pct}%)\nRecompensa hoje: R$ ${doneMoney}\n\nAmanhã (${tp[0]} — ${tp[1]}):\n- ${tp[3].map(x=>x[0]).join('\n- ')}\n\nRecomendação especial:\n- ${extra}\n\nPergunta para IA externa:\nCrie 5 exercícios simples para João Miguel, 9º ano, focando em ${c}, com respostas e explicações curtas.`;save()}
function renderAI(){if(!state.aiPlan)generateAIPlan();tutorText.textContent=`Prioridade do boletim: ${critical()}. A automação local gerou um plano de estudo e um relatório para IA externa.`;automationBox.innerHTML=`<b>Automação ativa</b><br><small>Plano atualizado conforme boletim, tarefas e calendário.</small>`;aiPrompt.value=state.aiPlan;tomorrowPlan.innerHTML=`<div class="automation-box">${state.aiPlan.replaceAll('\n','<br>')}</div>`;document.getElementById('critical').textContent=critical()}
function renderChallenge(){let all=Object.entries(qs).flatMap(([s,a])=>a.map(q=>({s,q})));let x=all[new Date().getDate()%all.length];challenge.innerHTML=`<p><b>${x.s}</b></p><p>${x.q[0]}</p>`+x.q[1].map((a,i)=>`<button class="answer" data-sub="${x.s}" data-i="${i}">${a}</button>`).join('')+`<div id="fb" class="feedback hidden"></div>`;window.current=x}
function renderCalendar(){let n=new Date(),y=n.getFullYear(),m=n.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0);let h=['D','S','T','Q','Q','S','S'].map(x=>`<div class="head">${x}</div>`).join('');let cells='';for(let i=0;i<first.getDay();i++)cells+='<button class="day empty"></button>';for(let day=1;day<=last.getDate();day++){let d=new Date(y,m,day),key=iso(d),dow=d.getDay(),cls='',icon=day;if(state.money[key]){cls='done';icon='🟢'}else if(dow===0||dow===6){cls='cateDay';icon='✝️'}else if(dow===5){cls='boss';icon='🏆'}else cls='miss';cells+=`<button class="day ${cls}" data-date="${key}">${icon}<br><small>${day}</small></button>`}month.innerHTML=`<div class="daygrid">${h}${cells}</div>`}
function renderAnnual(){let y=new Date().getFullYear();let names=['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];annualCalendar.innerHTML=`<div class="annual-grid">`+names.map((name,m)=>{let first=new Date(y,m,1),last=new Date(y,m+1,0);let heads=['D','S','T','Q','Q','S','S'].map(x=>`<div class="head">${x}</div>`).join('');let cells='';for(let i=0;i<first.getDay();i++)cells+='<button class="mini-day empty"></button>';for(let day=1;day<=last.getDate();day++){let d=new Date(y,m,day),p=plan(d);cells+=`<button class="mini-day ${p[2]}" data-annual="${iso(d)}">${day}</button>`}return `<div class="month-card"><h3>${name}</h3><div class="mini-grid">${heads}${cells}</div></div>`}).join('')+`</div>`}
function describeDate(key,target='dayDetails'){let d=new Date(key+'T00:00:00'),p=plan(d),s=stats(d);let html=`<b>${p[0]} — ${key}</b><br><small>Eixo: ${p[1]} • Progresso: ${s.done}/${s.total}</small><ul>${p[3].map(t=>`<li><b>${t[0]}</b>: ${t[1]}</li>`).join('')}</ul>`;document.getElementById(target).innerHTML=html}
function renderWeek(){weekView.innerHTML=weekDates().map(d=>{let p=plan(d),s=stats(d);return`<div class="week"><b>${p[0]} — ${p[1]}</b><br><small>${s.done}/${s.total} tarefas</small><ul>${p[3].map(t=>`<li>${t[0]}</li>`).join('')}</ul></div>`}).join('')}
function renderAcademy(){curriculum.innerHTML=Object.entries(curriculum).map(([s,it])=>`<div class="item"><b>${subjectIcons[s]||'📚'} ${s}</b><br><small>${it.join(' • ')}</small></div>`).join('');subjects.innerHTML=Object.keys(qs).map(s=>`<button class="subject" data-subject="${s}">${subjectIcons[s]||'📚'} ${s}</button>`).join('')}
function renderCate(){catePlan.innerHTML=[['Sábado','Ler uma seção do Catecismo de São Pio X e responder 3 perguntas.'],['Domingo','Missa, orações e revisão breve.'],['Sequência','Doutrina Cristã → Credo → Oração → Mandamentos → Sacramentos → Virtudes.']].map(x=>`<div class="cate"><b>${x[0]}</b><br><small>${x[1]}</small></div>`).join('')}
function gradesData(){return gradesDataArr.map(g=>`<div class="grade"><b>${g[0]}</b><br><small>Nota ${g[1].toFixed(1)} • peso ${g[2]}</small></div>`).join('')}
function renderJourney(){let i=state.journeyIndex||0,p=journeyPages[i];journeyContent.innerHTML=`<div class="journey-slide"><div class="journey-emoji pulse">${p.emoji}</div><h3>${p.title}</h3><p>${p.text}</p><div class="journey-progress">${i+1} de ${journeyPages.length}</div></div>`;journeyPrev.disabled=i===0;journeyNext.textContent=i===journeyPages.length-1?'Começar minha missão 🚀':'Próximo ▶'}
function renderAchievements(){let missions=Object.keys(state.money).length;let xpVal=state.xp;let achievements=[['🥉 Primeira missão',missions>=1,'Aprovar a primeira missão diária.'],['🧮 Mestre da Matemática',xpVal>=25,'Conquistar 25 XP em exercícios.'],['💰 Guardião do Tesouro',state.piggy.saved>=20,'Guardar R$ 20 na meta.'],['🦅 Águia da Constância',missions>=5,'Completar 5 missões.'],['🏛 Guardião do Trivium',xpVal>=50,'Alcançar 50 XP.']];achievementList.innerHTML=achievements.map(a=>`<div class="achievement ${a[1]?'done':'locked'}"><b>${a[0]}</b><br><small>${a[2]}</small></div>`).join('');campaignMap.innerHTML=['Aspirante','Escudeiro','Estudioso','Discípulo','Águia Jovem','Guardião','Águia Imperial'].map((n,i)=>`<div class="campaign-step ${xpVal>=i*50?'done':'locked'}"><b>${i+1}. ${n}</b><br><small>${xpVal>=i*50?'Desbloqueado':'Faltam '+Math.max(0,i*50-xpVal)+' XP'}</small></div>`).join('')}
function approve(){let s=stats();if(!s.complete){approval.textContent='A missão ainda não está completa.';return}if(state.money[today()]){approval.textContent='Missão já aprovada hoje.';return}state.money[today()]=10;state.xp+=10;state.piggy.free+=7;state.piggy.saved+=2;state.piggy.charity+=1;state.aiPlan='';save();approval.textContent='🦅 Missão aprovada. R$ 10 liberados.';renderAll()}
function renderAll(){renderMission();renderEagleMessage();renderAI();renderChallenge();renderCalendar();renderAnnual();renderWeek();renderAcademy();renderCate();renderJourney();renderAchievements();document.getElementById('grades').innerHTML=gradesData();weekMoney.textContent=money(weekMoney());xp.textContent=state.xp+' XP'}
document.addEventListener('change',e=>{if(e.target.matches('#tasks input')){state.checked[e.target.dataset.id]=e.target.checked;state.aiPlan='';save();renderAll()}})
document.addEventListener('click',e=>{if(e.target.matches('[data-tab]'))switchTab(e.target.dataset.tab);if(e.target.id==='goParent')switchTab('parent');if(e.target.id==='approve')approve();if(e.target.id==='runAI'){generateAIPlan();renderAll()}if(e.target.id==='copyAIPrompt'){aiPrompt.select();document.execCommand('copy');alert('Relatório copiado. Cole em uma IA externa para gerar exercícios personalizados.')}if(e.target.matches('[data-date]'))describeDate(e.target.dataset.date,'dayDetails');if(e.target.matches('[data-annual]'))describeDate(e.target.dataset.annual,'annualDetails');if(e.target.matches('[data-subject]')){let sub=e.target.dataset.subject,q=qs[sub][0];quiz.innerHTML=`<h3>${subjectIcons[sub]||'📚'} ${sub}</h3><p>${q[0]}</p>`+q[1].map((a,i)=>`<button class="answer" data-sub="${sub}" data-i="${i}">${a}</button>`).join('')+`<div id="qfb" class="feedback hidden"></div>`}if(e.target.matches('.answer')){let sub=e.target.dataset.sub,q=qs[sub][0],ok=Number(e.target.dataset.i)===q[2];e.target.classList.add(ok?'correct':'wrong');state.xp+=ok?5:0;state.answers[sub]=(state.answers[sub]||0)+1;let fb=document.getElementById('qfb')||document.getElementById('fb');fb.classList.remove('hidden');fb.textContent=ok?'✅ Correto! +5 XP':'❌ '+q[3];state.aiPlan='';save();renderAll()}if(e.target.id==='journeyNext'){if(state.journeyIndex<journeyPages.length-1){state.journeyIndex++;save();renderJourney()}else{localStorage.setItem('journeySeenV10','done');switchTab('today')}}if(e.target.id==='journeyPrev'){if(state.journeyIndex>0){state.journeyIndex--;save();renderJourney()}}if(e.target.id==='restartJourney'){state.journeyIndex=0;save();renderJourney()}if(e.target.id==='export'){let blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='projeto-aguia-v10-progresso.json';a.click()}if(e.target.id==='logout'){localStorage.removeItem('unlockedV10');location.reload()}})
if('serviceWorker' in navigator)navigator.serviceWorker.register('service-worker.js');
renderAll();
