
const PASSWORD='aguia2026';
const gradesDataArr=[['Matemática',3.3,5],['Inglês',3.3,5],['Projeto',3.3,5],['Ciências',5.0,4],['Arte',5.0,3],['Português',6.7,2],['Geografia',6.0,1],['História',7.3,1]];
const subjectIcons={'Matemática':'🧮','Inglês':'🇺🇸','Projeto':'💡','Catecismo':'✝️','Latim':'🏛️','Ed. Financeira':'💰','Português':'📝','Ciências':'🔬','Geografia':'🌎','História':'🏛️','Arte':'🎨'};
const curriculum={Matemática:['Porcentagem','Equações','Funções','Estatística','Geometria'],Português:['Interpretação textual','Produção textual','Gramática contextualizada'],Ciências:['Genética','Ecologia','Corpo humano'],História:['República Brasileira','Guerras Mundiais'],Geografia:['Globalização','Geopolítica'],Inglês:['Reading','Vocabulário','Verbos'],Arte:['Artes visuais','Música'],Projeto:['Pesquisa','Fontes','Apresentação oral']};
const plans={1:['Segunda-feira','Gramática','gram',[['Português','Interpretação e gramática'],['Inglês','Vocabulário e reading'],['Rosetta Stone','20 minutos'],['Latim','Oração do mês'],['Exercício','Quiz de gramática'],['Finanças','Registrar recompensa se aprovado']]],2:['Terça-feira','Dialética','dial',[['Matemática','Porcentagem, equações ou funções'],['Ciências','Genética, ecologia ou corpo humano'],['Educação Financeira','Problema prático'],['Exercício','Quiz de raciocínio'],['Revisão','Questões erradas'],['Virtude','Perseverança']]],3:['Quarta-feira','Retórica','rhet',[['Projeto','Pesquisa e organização'],['Português','Produção de texto curto'],['Apresentação oral','Explicar ao responsável'],['Inglês','Frases simples'],['Diário Águia','O que aprendi hoje?'],['Exercício','Argumentação']]],4:['Quinta-feira','Quadrivium','quad',[['Geometria','Número no espaço'],['Geografia','Mapas, economia ou ambiente'],['Arte','Forma, imagem e proporção'],['Astronomia/Ciências','Tempo e movimento'],['Latim cantado','Gloria Patri'],['Exercício','Quiz do Quadrivium']]],5:['Sexta-feira','Síntese','syn',[['Revisão geral','Matemática, Inglês e Projeto'],['Boss Battle','20 questões'],['Simulado curto','3º/4º bimestre'],['Organização','Material e pendências'],['Relatório','Responsável confere'],['Diário','Fechamento semanal']]],6:['Sábado','Catecismo','cat',[['Catecismo','Leitura anual de São Pio X'],['Perguntas','3 perguntas e respostas'],['Oração','Credo ou Sinal da Cruz'],['Reflexão','O que aprendi sobre Deus?'],['Latim','Uma oração em latim']]],0:['Domingo','Vida Cristã','cat',[['Missa','Participar da Santa Missa'],['Revisão dominical','Relembrar a leitura de sábado'],['Orações','Pai Nosso, Ave Maria, Glória e Salve Rainha'],['Diário espiritual','Gratidão e propósito'],['Família','Conversar sobre a semana']]]};
const qs={Matemática:[['15% de 200 é:',['15','20','30','50'],2,'15% = 0,15; 0,15 × 200 = 30.']],Inglês:[['Book significa:',['Mesa','Livro','Casa','Caneta'],1,'Book = livro.']],Projeto:[['Um projeto começa com:',['Cópia','Pergunta ou problema','Atraso'],1,'Começa com uma pergunta/problema.']],Catecismo:[['As partes principais da Doutrina Cristã são:',['Credo, Padre-Nosso, Mandamentos e Sacramentos','Somente Latim','Somente História'],0,'São quatro partes principais.']],Latim:[['Cognoscere significa:',['Conhecer','Amar','Servir'],0,'Cognoscere = conhecer.']],'Ed. Financeira':[['20% de R$10 é:',['R$1','R$2','R$5'],1,'20% de 10 = R$2.']],Português:[['Interpretar é:',['Copiar','Compreender','Somar'],1,'Interpretar é compreender.']],Ciências:[['DNA está ligado a:',['Genética','Música','Mapa'],0,'DNA é genética.']]};
const cateThemes=['Introdução e Orações','Persignar-se e Sinal da Cruz','Credo','Padre Nosso','Ave Maria','Salve Rainha e Glória','Mandamentos da Lei de Deus','Mandamentos da Igreja','Sacramentos','Doutrina Cristã','O que é ser cristão','Partes da Doutrina Cristã','Credo em geral','Primeiro artigo do Credo','Deus Pai Criador','Os Anjos','Anjo da Guarda','O homem','A alma','Liberdade humana','Pecado original','Promessa do Redentor','Jesus Cristo Nosso Senhor','Encarnação','Paixão de Cristo','Ressurreição','Ascensão','Espírito Santo','Igreja Católica','Comunhão dos Santos','Remissão dos Pecados','Ressurreição da Carne','Vida Eterna','A Oração','Padre Nosso explicado','Mandamentos de Deus','Amar a Deus','Honrar pai e mãe','Não matar e pureza','Não furtar e verdade','Mandamentos da Igreja','Sacramentos em geral','Batismo','Confirmação','Eucaristia','Penitência','Extrema Unção e Ordem','Matrimônio','Virtudes principais','Pecado e vícios','Bem-aventuranças','Obras de Misericórdia','Novíssimos e Perseverança'];
const cateTexts=[
'Este primeiro encontro apresenta as principais orações e fórmulas da doutrina católica. O objetivo é entender que a fé deve ser conhecida, amada e vivida com constância.',
'Persignar-se é pedir proteção a Deus pelo sinal da Santa Cruz. Pelo sinal da santa cruz, livrai-nos, Deus nosso Senhor, dos nossos inimigos.',
'O Credo resume as principais verdades da fé cristã. Rezar o Credo ajuda a gravar no coração aquilo que a Igreja ensina.',
'O Padre Nosso ensina tudo o que devemos esperar de Deus e tudo o que devemos pedir a Ele.',
'A Ave Maria honra a Mãe de Deus e pede sua intercessão agora e na hora da nossa morte.',
'A Salve Rainha, o Glória e outras orações ajudam a alma a louvar a Deus e pedir auxílio à Virgem Maria.',
'Os Mandamentos da Lei de Deus são dez e se resumem em amar a Deus sobre todas as coisas e ao próximo como a nós mesmos.',
'Os Mandamentos da Igreja orientam a vida do cristão dentro da Santa Igreja.',
'Os Sacramentos são sete meios instituídos por Jesus Cristo para comunicar a graça.',
'A Doutrina Cristã é a doutrina ensinada por Jesus Cristo para nos mostrar o caminho da salvação.'
];
const journeyPages=[{emoji:'🦅',title:'Olá, João!',text:'Eu sou a Águia. Vou acompanhar você na sua jornada.'},{emoji:'✝️',title:'Catecismo Anual',text:'Todos os sábados você dará um passo na fé com São Pio X.'},{emoji:'🚀',title:'Começar',text:'Cognoscere, amare et servire Deum.'}];
let state=JSON.parse(localStorage.getItem('aguiaV11')||'{"checked":{},"money":{},"xp":0,"cateDone":{},"catePage":0,"cateXP":0,"piggy":{"free":0,"saved":0,"charity":0,"goal":500},"journeyIndex":0,"aiPlan":""}');
function save(){localStorage.setItem('aguiaV11',JSON.stringify(state))}
function iso(d){return d.toISOString().slice(0,10)} function today(){return iso(new Date())} function money(n){return 'R$ '+Number(n).toFixed(0)} function plan(d){return plans[d.getDay()]} function tid(d,i){return iso(d)+'-'+i}
function stats(d=new Date()){let p=plan(d),done=0;p[3].forEach((_,i)=>{if(state.checked[tid(d,i)])done++});return{done,total:p[3].length,pct:Math.round(done/p[3].length*100),complete:done===p[3].length}}
function critical(){return gradesDataArr.slice().sort((a,b)=>a[1]-b[1])[0][0]} function weekMoney(){return Object.values(state.money).reduce((a,b)=>a+b,0)}
function switchTab(tab){document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));document.getElementById(tab).classList.add('active');document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));renderAll()}
enter.onclick=()=>{if(pass.value===PASSWORD){localStorage.setItem('unlockedV11','yes');lock.classList.add('hidden');app.classList.remove('hidden')}else alert('Senha incorreta')};if(localStorage.getItem('unlockedV11')==='yes'){lock.classList.add('hidden');app.classList.remove('hidden')}
function saturdaysOfYear(){let y=new Date().getFullYear(),d=new Date(y,0,1),arr=[];while(d.getFullYear()===y){if(d.getDay()===6)arr.push(new Date(d));d.setDate(d.getDate()+1)}return arr.slice(0,52)}
function cateWeekIndex(date=new Date()){let sats=saturdaysOfYear();let idx=sats.findIndex(s=>iso(s)>=iso(date)); if(idx<0) idx=51; return idx}
function cateDoneCount(){return Object.keys(state.cateDone).length}
function renderMission(){let d=new Date(),p=plan(d),s=stats(d);todayTitle.textContent=p[0]+' — '+p[1];tasks.innerHTML=p[3].map((t,i)=>`<label class="task"><input type="checkbox" data-id="${tid(d,i)}" ${state.checked[tid(d,i)]?'checked':''}><span><b>${t[0]}</b><small>${t[1]}</small></span></label>`).join('');dayPct.textContent=s.pct+'%';dayBar.style.width=s.pct+'%';todayMoney.textContent=state.money[today()]?money(10):'R$ 0';missionText.textContent=s.complete?'Missão completa. Peça aprovação.':'Complete tudo para liberar R$ 10.';tasksDone.textContent=s.done+'/'+s.total}
function renderEagleMessage(){let s=stats(),p=plan(new Date());eagleMessage.textContent=new Date().getDay()===6?'Hoje é sábado: avance na Jornada Anual do Catecismo.':`Hoje é dia de ${p[1]}. Faltam ${Math.max(0,s.total-s.done)} tarefa(s).`}
function generateAIPlan(){let c=critical(),idx=cateWeekIndex(),theme=cateThemes[idx]||cateThemes[0];let tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+1);let tp=plan(tomorrow);state.aiPlan=`Plano automático do Projeto Águia V11\\n\\nPrioridade escolar: ${c}\\nCatecismo: ${cateDoneCount()}/52 sábados concluídos\\nTema atual do Catecismo: ${theme}\\n\\nAmanhã (${tp[0]} — ${tp[1]}):\\n- ${tp[3].map(x=>x[0]).join('\\n- ')}\\n\\nPedido para IA externa:\\nCrie 5 exercícios simples para João Miguel, 9º ano, sendo 3 sobre ${c} e 2 sobre o tema do Catecismo: ${theme}. Inclua respostas e explicações curtas.`;save()}
function renderAI(){if(!state.aiPlan)generateAIPlan();tutorText.textContent=`Prioridade: ${critical()}. Catecismo anual: ${cateDoneCount()}/52 sábados.`;automationBox.innerHTML='<b>Automação ativa</b><br><small>Inclui agora o progresso do Catecismo de São Pio X.</small>';aiPrompt.value=state.aiPlan;tomorrowPlan.innerHTML=`<div class="automation-box">${state.aiPlan.replaceAll('\\n','<br>')}</div>`;critical.textContent=critical()}
function renderChallenge(){let all=Object.entries(qs).flatMap(([s,a])=>a.map(q=>({s,q})));let x=all[new Date().getDate()%all.length];challenge.innerHTML=`<p><b>${x.s}</b></p><p>${x.q[0]}</p>`+x.q[1].map((a,i)=>`<button class="answer" data-sub="${x.s}" data-i="${i}">${a}</button>`).join('')+`<div id="fb" class="feedback hidden"></div>`;window.current=x}
function renderAnnual(){let y=new Date().getFullYear();let names=['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];annualCalendar.innerHTML=`<div class="annual-grid">`+names.map((name,m)=>{let first=new Date(y,m,1),last=new Date(y,m+1,0);let heads=['D','S','T','Q','Q','S','S'].map(x=>`<div class="head">${x}</div>`).join('');let cells='';for(let i=0;i<first.getDay();i++)cells+='<button class="mini-day empty"></button>';for(let day=1;day<=last.getDate();day++){let d=new Date(y,m,day),p=plan(d),key=iso(d),done=state.cateDone[key]?' ✅':'';cells+=`<button class="mini-day ${p[2]}" data-annual="${key}">${day}${done}</button>`}return `<div class="month-card"><h3>${name}</h3><div class="mini-grid">${heads}${cells}</div></div>`}).join('')+`</div>`}
function describeDate(key,target='annualDetails'){let d=new Date(key+'T00:00:00'),p=plan(d),s=stats(d);let extra=d.getDay()===6?`<br><b>Leitura do Catecismo:</b> Semana ${saturdaysOfYear().findIndex(x=>iso(x)===key)+1}`:'';document.getElementById(target).innerHTML=`<b>${p[0]} — ${key}</b><br><small>Eixo: ${p[1]} • Progresso: ${s.done}/${s.total}</small>${extra}<ul>${p[3].map(t=>`<li><b>${t[0]}</b>: ${t[1]}</li>`).join('')}</ul>`}
function renderCatechism(){let done=cateDoneCount(),pct=Math.round(done/52*100);cateProgress.textContent=pct+'%';cateDone.textContent=done+'/52';cateXP.textContent=state.cateXP+' XP';cateBar.style.width=pct+'%';cateMedal.textContent=done>=52?'Águia da Fé':done>=40?'Guardião da Doutrina':done>=25?'Discípulo de São Pio X':done>=10?'Pequeno Catequista':'Primeiro Sábado';renderCateReader();let sats=saturdaysOfYear();cateSchedule.innerHTML=sats.map((d,i)=>{let key=iso(d),done=state.cateDone[key];return`<div class="cate-week ${done?'done':'locked'}"><b>${i+1}. ${key}</b><br><small>${cateThemes[i]||'Revisão'} • págs. ${i*4+1}-${i*4+4}</small><br><button data-open-cate="${i}">Abrir</button></div>`}).join('');sundayReview.innerHTML='<div class="reader"><b>Revisão Dominical</b><ul><li>Relembrar a leitura de sábado.</li><li>Responder 3 perguntas.</li><li>Rezar a oração da semana.</li><li>Conversar com a família.</li></ul></div>';parentCatechism.innerHTML=`<div class="reader"><b>Progresso: ${done}/52 sábados</b><br><small>${pct}% concluído • ${state.cateXP} XP de Catecismo</small></div>`}
function renderCateReader(){let i=state.catePage||0,theme=cateThemes[i]||cateThemes[0],txt=cateTexts[i%cateTexts.length],sats=saturdaysOfYear(),key=iso(sats[i]||sats[0]);cateReader.innerHTML=`<div class="reader"><h3>Semana ${i+1}: ${theme}</h3><small>Sábado: ${key} • páginas ${i*4+1}-${i*4+4}</small><div class="reader-text">${txt}<br><br><b>Pergunta:</b> O que esta leitura ensina sobre conhecer, amar e servir a Deus?</div><div class="reader-controls"><button id="prevCate" class="secondary">◀ Anterior</button><button id="nextCate">Próxima ▶</button><button id="markCate" class="full">☑ Concluir leitura deste sábado</button></div></div>`}
function renderAcademy(){curriculum.innerHTML=Object.entries(curriculum).map(([s,it])=>`<div class="item"><b>${subjectIcons[s]||'📚'} ${s}</b><br><small>${it.join(' • ')}</small></div>`).join('');subjects.innerHTML=Object.keys(qs).map(s=>`<button class="subject" data-subject="${s}">${subjectIcons[s]||'📚'} ${s}</button>`).join('')}
function gradesData(){return gradesDataArr.map(g=>`<div class="grade"><b>${g[0]}</b><br><small>Nota ${g[1].toFixed(1)} • peso ${g[2]}</small></div>`).join('')}
function renderJourney(){let i=state.journeyIndex||0,p=journeyPages[i];journeyContent.innerHTML=`<div class="journey-slide"><div class="journey-emoji">${p.emoji}</div><h3>${p.title}</h3><p>${p.text}</p><div class="journey-progress">${i+1} de ${journeyPages.length}</div></div>`;journeyPrev.disabled=i===0;journeyNext.textContent=i===journeyPages.length-1?'Começar 🚀':'Próximo ▶'}
function renderAchievements(){let missions=Object.keys(state.money).length,done=cateDoneCount();let achievements=[['🥉 Primeira missão',missions>=1,'Aprovar a primeira missão.'],['✝️ Primeiro Sábado',done>=1,'Concluir a primeira leitura.'],['📖 Pequeno Catequista',done>=10,'Concluir 10 sábados.'],['🏛 Discípulo de São Pio X',done>=25,'Concluir 25 sábados.'],['🦅 Águia da Fé',done>=52,'Concluir 52 sábados.']];achievementList.innerHTML=achievements.map(a=>`<div class="achievement ${a[1]?'done':'locked'}"><b>${a[0]}</b><br><small>${a[2]}</small></div>`).join('')}
function approve(){let s=stats();if(!s.complete){approval.textContent='A missão ainda não está completa.';return}if(state.money[today()]){approval.textContent='Missão já aprovada hoje.';return}state.money[today()]=10;state.xp+=10;state.piggy.free+=7;state.piggy.saved+=2;state.piggy.charity+=1;state.aiPlan='';save();approval.textContent='🦅 Missão aprovada. R$ 10 liberados.';renderAll()}
function renderAll(){renderMission();renderEagleMessage();renderAI();renderChallenge();renderAnnual();renderCatechism();renderAcademy();renderJourney();renderAchievements();grades.innerHTML=gradesData();weekMoney.textContent=money(weekMoney());xp.textContent=state.xp+' XP'}
document.addEventListener('change',e=>{if(e.target.matches('#tasks input')){state.checked[e.target.dataset.id]=e.target.checked;state.aiPlan='';save();renderAll()}})
document.addEventListener('click',e=>{if(e.target.matches('[data-tab]'))switchTab(e.target.dataset.tab);if(e.target.id==='goParent')switchTab('parent');if(e.target.id==='approve')approve();if(e.target.id==='runAI'){generateAIPlan();renderAll()}if(e.target.id==='copyAIPrompt'){aiPrompt.select();document.execCommand('copy');alert('Relatório copiado.')}if(e.target.matches('[data-annual]'))describeDate(e.target.dataset.annual);if(e.target.matches('[data-subject]')){let sub=e.target.dataset.subject,q=qs[sub][0];quiz.innerHTML=`<h3>${subjectIcons[sub]||'📚'} ${sub}</h3><p>${q[0]}</p>`+q[1].map((a,i)=>`<button class="answer" data-sub="${sub}" data-i="${i}">${a}</button>`).join('')+`<div id="qfb" class="feedback hidden"></div>`}if(e.target.matches('.answer')){let sub=e.target.dataset.sub,q=qs[sub][0],ok=Number(e.target.dataset.i)===q[2];e.target.classList.add(ok?'correct':'wrong');state.xp+=ok?5:0;let fb=document.getElementById('qfb')||document.getElementById('fb');fb.classList.remove('hidden');fb.textContent=ok?'✅ Correto! +5 XP':'❌ '+q[3];state.aiPlan='';save();renderAll()}if(e.target.id==='continueCatechism'){switchTab('catechism');state.catePage=cateWeekIndex();save();renderAll()}if(e.target.matches('[data-open-cate]')){state.catePage=Number(e.target.dataset.openCate);save();renderAll();window.scrollTo(0,0)}if(e.target.id==='prevCate'){state.catePage=Math.max(0,(state.catePage||0)-1);save();renderAll()}if(e.target.id==='nextCate'){state.catePage=Math.min(51,(state.catePage||0)+1);save();renderAll()}if(e.target.id==='markCate'){let i=state.catePage||0,key=iso(saturdaysOfYear()[i]);if(!state.cateDone[key]){state.cateDone[key]=true;state.cateXP+=10;state.xp+=10;state.aiPlan='';save()}renderAll()}if(e.target.id==='journeyNext'){if(state.journeyIndex<journeyPages.length-1){state.journeyIndex++;save();renderJourney()}else switchTab('today')}if(e.target.id==='journeyPrev'){if(state.journeyIndex>0){state.journeyIndex--;save();renderJourney()}}if(e.target.id==='restartJourney'){state.journeyIndex=0;save();renderJourney()}if(e.target.id==='export'){let blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='projeto-aguia-v11-progresso.json';a.click()}if(e.target.id==='logout'){localStorage.removeItem('unlockedV11');location.reload()}})
if('serviceWorker' in navigator)navigator.serviceWorker.register('service-worker.js');
renderAll();
